### ISSUE TITLE
No such file or directory: './data/input/input0.npy'

### ISSUE THREAD

**Issue by clttyou** [kyoukuntaro/StereoSR_Jeon_CVPR2018#2]

**Comment by Tetsujinfr** [comment]
hi @clttyou 
did you found a solution to this problem? I got the same issue. thanks a lot

**Comment by Tetsujinfr** [comment]
Ok found the root cause. Sharing solution for the greater good here.

So the code process the Flickr1024 dataset if not already done, so typically the first time you run the code successfully.
Now, when preparing the data, the code check if a folder "data" exists or not, if not it does kickoff the data processing step, otherwise it skips it and goes to the training directly.

It is quite unlikely a user will successfully run the training successfully the first time, e.g. due to typo in the readme instructions or due to an inaccurate data folder argument you pass, and if so, the train.py code is going to create a "data" subfolder and crash. Then when you try again to run the train the data processing step is skipped because the data folder has been created previously (even if it is still empty due to the previous crash).

So if you face this error `No such file or directory: './data/input/input0.npy'`, it means the data processing step has not  succeded yet, i.e. your "data folder has no file in it, and you need to delete it so that the code is forced to process it again.

Not a difficult tweak but good luck!

_ps: also, do not store the flick1024 images in a subfolder named "data" like I did initially, since this is the name of the subfolder the processing step creates._
